### ISSUE TITLE
404 Issue

### ISSUE THREAD

**Issue by pfifo** [googlecodelabs/webrtc-web#26]
Step 4 adds the line
`<script src="/socket.io/socket.io.js"></script>`
to index.html
However this file is not provided by repo and no information is given on how to go about installing it.

**Comment by nitobuendia** [comment]
Hello @pfifo,

Currently, we have the following explanation:
![screen shot 2017-11-28 at 23 19 19](https://user-images.githubusercontent.com/16522489/33327502-9bb0205c-d492-11e7-9f0a-1b73e80c42b2.png)

When running npm install from the same server, it should solve the issue with socket.io

Would that be enough? Anything that would make it clearer for you and future readers?

Thanks!

**Comment by pfifo** [comment]
pfifo@desktop:~$ npm install
bash: npm: command not found

Still getting the 404... additionally, npm is not installed, and will remain not installed... this is a LAMP stack and I refuse to believe web-rtc, a client-side library, requires anything to be installed on the server.

If the developers are unable to write a tutorial for a client-side library that dosent require root privileges... then, fact of the matter, they are not qualified to be called developers.

**Comment by nitobuendia** [comment]
@pfifo 

It is working as intended.

Steps 1-3 are client-side only and you can examine the APIs and test it without node.js

However, steps 4-5 requires node.js to manage the dependencies that the codelab uses.
This is specified on the same codelab:
![screen shot 2017-11-29 at 20 22 57](https://user-images.githubusercontent.com/16522489/33374938-25845fae-d543-11e7-834a-0105a6bb9797.png)

Therefore, if you do not install node.js, run "npm install" on the folder (where index.js) is and then run "node index.js" this is expected not to work. All these instructions are gathered on step 4 ([number 7](https://codelabs.developers.google.com/codelabs/webrtc-web/#6)).

If you are interested on those steps, you can download node.js [here](https://nodejs.org/en/download/) or [install it](https://nodejs.org/en/download/package-manager/) using different package management systems. On #23, they have requested adding details on how to install node.js and I think it is a fair idea to have a small section explaining this further.

**Comment by samdutton** [comment]
>  I refuse to believe web-rtc, a client-side library, requires anything to be installed on the server

Just to be clear, WebRTC uses a client-side JavaScript API, but for real-world usage also requires a signaling (messaging) server, as well as STUN and TURN servers. You can find out more [here](https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/).

I'll close this now, but feel free to open another issue if you're still experiencing problems.
